services:

  gateway:
    image: kong/kong-gateway:3.2.2.0-alpine
    container_name: gateway
    restart: on-failure
    networks:
      - app
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
      - "8004:8004"
      - "8443:8443"
      - "8444:8444"
      - "8445:8445"
    volumes:
      - ./kong.yml:/etc/kong/kong.yml:ro
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/etc/kong/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_URL=http://localhost:8002
    depends_on:
      - api
    links:
      - api

  api:
    image: wkas/glassdoor-hr-review-detector-api:1
    container_name: api
    restart: always
    networks:
      - app
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      GDHR_INFERENCE_API_ENDPOINT: http://inference:8501/v1/models/glassdoor_hr_review_detector:predict
    depends_on:
      - inference

  inference:
    image: wkas/glassdoor-hr-review-detector-inference:1
    container_name: inference
    restart: always
    networks:
      - app
    ports:
      - "8501:8501"

networks:
  app: